MATCHED_DATA_UPDATE_STRING = "update matched_data set  \
                            potential_matched_url = :potential_matched_url,\
                            hamming_score =:hamming_score,\
                            tokens =:tokens,\
                            hit_count =:hit_count,\
                            token_position =:token_position,\
                            token_count =:token_count,\
                            service_providing_system =:service_providing_system, \
                            final_matched_url =:final_matched_url, \
                            auto_matched =:auto_matched, \
                            auto_matched_verified =:auto_matched_verified, \
                            false_positive =:false_positive, \
                            housekeep_raw_data =:housekeep_raw_data \
                            where id = :id"
RAW_DATA_UPDATE_STRING = "update raw_data set  \
                                hit_count = :hit_count,\
                                matched_data_id =:matched_data_id,\
                                raw_url =:raw_url,\
                                service_providing_system =:service_providing_system,\
                                service_using_system =:service_using_system,\
                                token_count =:token_count,\
                                tokens =:tokens \
                                where id = :id"